name: JavaLoader
main: io.github.pieter12345.javaloader.bukkit.JavaLoaderBukkitPlugin
version: ${version}
author: Pieter12345/Woesh0007
load: postworld
api-version: 1.13
commands:
    javaloader:
        description: This plugin can compile, load, unload and hotswap java projects in runtime.
        usage: /javaloader <recompile, load, unload> [project]
        permission: javaloader.use
        permission-message: You don't have permission to use this command.