name: EccsJavaLoader
main: io.github.pieter12345.javaloader.bukkit.JavaLoaderBukkitPlugin
version: ${version}
authors:
    - Pieter12345/Woesh0007
    - Ecconia
load: POSTWORLD
api-version: 1.13
commands:
    javaloaderecc:
        description: This plugin can compile, load, unload and hotswap java projects in runtime.
        permission: eccsjavaloader.use
        permission-message: You do not have permission to use this command.
